server {
    listen 80;
    server_tokens off;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /static/admin/ {
        root /var/html/;
    }
    location /media/ {
        alias /var/html/media/;
    }

    location / {
        root /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
